Not what I expected!
Changed saveOrUpdate in Nationality test and got the following error
org.hibernate.AnnotationException: Use of @OneToMany or @ManyToMany targeting an unmapped class: entity.InstrumentCategory.instruments[entity.Instrument]

Will go investigate cause...